#!/bin/sh
set -e

case "$1" in
	remove)
		socksproxy stop > /dev/null 2>&1 || true		
		;;
		
	upgrade|deconfigure|failed-upgrade)
		;;

	*)
		echo "prerm called with unknown argument \`$1'" >&2
		exit 0
		;;
esac

#DEBHELPER#

exit 0
