#!/bin/bash

### BEGIN INIT INFO
# Provides:          socksproxy
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple SOCKS proxy
# Description:       Simple SOCKS proxy
### END INIT INFO

. /lib/lsb/init-functions

case "$1" in
	start|stop|status|restart)
		socksproxy "$@"			
		;;

	force-reload|reload)
		;;
			
	*)
		echo "socksproxy init script called with unknown argument '$1'" >&2
		exit 1
		;;
esac

